CREATE TYPE "TariffDayType" AS ENUM ('ALL', 'WEEKDAY', 'WEEKEND', 'HOLIDAY');

CREATE TYPE "BillingCalculationType" AS ENUM ('HOURLY', 'FLAT', 'ZERO');

ALTER TABLE "Organization"
ADD COLUMN "isBillingRelevant" BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE "Tariff"
ADD COLUMN "dayType" "TariffDayType" NOT NULL DEFAULT 'ALL';

ALTER TABLE "BillingEntry"
ADD COLUMN "periodStart" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN "periodEnd" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN "durationMinutes" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "unitPrice" DECIMAL(10,2),
ADD COLUMN "calculationType" "BillingCalculationType" NOT NULL DEFAULT 'ZERO';
